### ISSUE TITLE
PNG symbol shows instead of the icon

### ISSUE THREAD

**Issue by infinitepower18** [niw/GoodMacAppIcon#2]
<img width="742" alt="Screenshot 2024-06-07 at 5 40 37 PM" src="https://github.com/niw/GoodMacAppIcon/assets/44692189/dda458d9-a15e-4bce-9d06-4ace75ad0d58">

**Comment by niw** [comment]
Yeah, it's not supporting dropping image as image yet and I know current behavior is not expected.

**Comment by niw** [comment]
Okay, this issue should be fixed on [0.1.1 release](https://github.com/niw/GoodMacAppIcon/releases/tag/0.1.1).
